### ISSUE TITLE
Is it possible to restore a drawing's state (undo stack and so on)?

### ISSUE THREAD

**Issue by JulianHidalgo** [Leimi/drawingboard.js#46]
I'd like to give my users the option to save the drawing and then keep editing later on. Thanks :)!

**Comment by Leimi** [comment]
Hey,

Besides the web storage feature, which save the current drawing in local or session storage, there is no such feature included currently. So, people can come back to their drawing later on, but they can't undo things after reloading the page because their history is not kept, only the current drawing.
