### ISSUE TITLE
Show all brush sizes?

### ISSUE THREAD

**Issue by username1290** [Leimi/drawingboard.js#67]
Is there a way to display all brush sizes all the time? 

example:
<img width="582" alt="Screen Shot 2019-12-14 at 5 00 PM" src="https://user-images.githubusercontent.com/2784323/70856126-6ca50000-1e93-11ea-9995-2a70749ddc07.png">

**Comment by manuhabitela** [comment]
There is no way by default without coding anything.

You could try maybe using the Size control with the "dropdown" type and adding some custom CSS in order to display it as you like, but I'm not sure this will be enough.

Another cleaner way of achieving this would be to create your own brush size control by taking inspiration at the [size control code](https://github.com/Leimi/drawingboard.js/blob/master/js/controls/size.js) in the "dropdown" type.

The main thing you'd have to change is the way the component renders in the `_dropdownTemplate` method.
